// <auto-generated />
using System;
using DSoft_Restaurant.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSoft_Restaurant.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250707121803_BoxTable")]
    partial class BoxTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categoroy");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBDeliveryCompany", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("DeliveryCompany");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBDeliveryEmployee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salaray")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("DeliveryEmployees");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBEmployeeCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EmployeeCategory");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBEmployees", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salaray")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBExpenses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBGroupExpenses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("GroupExpenses");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBItemDeliveryPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DeliveryCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DeliveryCompanyId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDeliveryPrices");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeight")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBTables", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBZones", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBEmployees", b =>
                {
                    b.HasOne("DSoft_Restaurant.Core.Model.TBEmployeeCategory", "TBEmployeeCategory")
                        .WithMany("TBEmployees")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TBEmployeeCategory");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBExpenses", b =>
                {
                    b.HasOne("DSoft_Restaurant.Core.Model.TBGroupExpenses", "TBGroupExpenses")
                        .WithMany("Expenses")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TBGroupExpenses");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBItemDeliveryPrice", b =>
                {
                    b.HasOne("DSoft_Restaurant.Core.Model.TBDeliveryCompany", "DeliverCompany")
                        .WithMany("ItemDeliveryPrices")
                        .HasForeignKey("DeliveryCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSoft_Restaurant.Core.Model.TBItems", "TBItems")
                        .WithMany("ItemDeliveryPrices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliverCompany");

                    b.Navigation("TBItems");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBItems", b =>
                {
                    b.HasOne("DSoft_Restaurant.Core.Model.TBCategory", "tBCategory")
                        .WithMany("items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tBCategory");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBTables", b =>
                {
                    b.HasOne("DSoft_Restaurant.Core.Model.TBZones", "TBZones")
                        .WithMany("tBTables")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TBZones");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBCategory", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBDeliveryCompany", b =>
                {
                    b.Navigation("ItemDeliveryPrices");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBEmployeeCategory", b =>
                {
                    b.Navigation("TBEmployees");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBGroupExpenses", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBItems", b =>
                {
                    b.Navigation("ItemDeliveryPrices");
                });

            modelBuilder.Entity("DSoft_Restaurant.Core.Model.TBZones", b =>
                {
                    b.Navigation("tBTables");
                });
#pragma warning restore 612, 618
        }
    }
}
